services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent-app
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ${TORRENTS_FOLDER}:/downloads
      - ./ipfilter.dat:/ipfilter.dat:ro
      - ${CONFIG_FOLDER:-./config}:/config
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 3000M
    networks:
      external:
        ipv4_address: ${QBITTORRENT_IP}

networks:
  external:
    external: true
    name: ${EXTERNAL_NETWORK_NAME}