services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    hostname: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${TORRENTS_FOLDER}:/downloads
      - ./ipfilter.dat:/ipfilter.dat:ro
      - ${CONFIG_FOLDER:-./config}:/config
    restart: unless-stopped
    networks:
      external:
        ipv4_address: ${QBITTORRENT_IP}

networks:
  external:
    external: true
    name: ${EXTERNAL_NETWORK_NAME}