services:
  qbittorrent:
    container_name: qbittorrent
    ports:
      - ${WEBUI_PORT:-8080}:${WEBUI_PORT:-8080}
      - ${TORRENTING_PORT:-6881}:${TORRENTING_PORT:-6881}/tcp
      - ${TORRENTING_PORT:-6881}:${TORRENTING_PORT:-6881}/udp
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - WEBUI_PORT=${WEBUI_PORT:-8080}
      - TORRENTING_PORT=${TORRENTING_PORT:-6881}
    volumes:
      - ${TORRENTS_FOLDER}:/downloads
      - ./ipfilter.dat:/ipfilter.dat:ro
      - config:/config
    image: lscr.io/linuxserver/qbittorrent:latest
    restart: unless-stopped
    networks:
      - net

networks:
  net:
    external: false

volumes:
  config:
    name: qbittorrent-config